name: 'Build Docker Image'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gen-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
