name: 'Build Docker Image'

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Build Image'
        run: docker build -t ghcr.io/mystarinyoursky/docker:latest .
