name: Scheduled Build and Push to Registry

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      FORCE_COLOR: 1
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
    - name: Run Task
      run: /bin/bash -c "buildscripts/scheduled_workflow.sh"
